export const NOTES={
    LOAD:"LOAD_NOTES",
    LOAD_SUCCESS:"LOAD_NOTES_SUCCESS",
    CREATE:"CREATE_NOTE",
    DELETE:"DELETE_NOTES",
    EDIT:"EDIT_NOTES",
    PIN:"PIN_NOTES",
    UNPIN:"UNPIN_NOTES",
    SORT:"SORT_NOTES"
}
export const CATEGORIES={
    LOAD:"LOAD_CATEGORIES",
    LOAD_SUCCESS:"LOAD_CATEGORIES_SUCCESS",
    ADD:"ADD_CATEGORIES",
    FETCH_NOTES:"FETCH_CATEGORY_NOTES"
}